config:
  accelerator: gpu
  batch_size: 512
  betas:
  - 0.9
  - 0.95
  block_size: 288
  checkpoint_every_n_train_steps: 100
  checkpoint_name: None
  devices: 2
  dim: 128
  dropout: 0.3
  grad_norm_clip: 1.0
  image_shape:
  - 48
  - 48
  inference_results_folder: ./inference_results/
  learning_rate: 0.0001
  log_dir: ./lightning_logs/vit_model/
  log_every_nsteps: 10
  lr_gamma: 0.999
  mask_prob: 0.0
  mode: min
  monitor: val_loss
  num_epochs: 10000
  num_heads: 8
  num_layers: 6
  num_workers: 10
  patch_dim: 4
  save_top_k: 4
  seed: 3407
  test_data_path: /home/mark/dev/aAlphaBio-Homework/data/val_set.csv
  train_data_path: /home/mark/dev/aAlphaBio-Homework/data/train_set.csv
  vocab_size: 24
