
model_params:
  block_size: 265    # can fit the max of 247 amino acids + CLS token + PAD tokens
                     # and be reshaped into a (46,46) single-channel tensor of 1's and 0's
  mask_prob: 0.0
  mlp_dropout : 0.2
  accelerator : 'gpu'
  devices: 1
  batch_size: 2048
  num_workers: 5
  grad_norm_clip : 1.0
  num_epochs : 10000
  log_dir : './lightning_logs/mlp_model/'
  train_data_path: '../data/train_set.csv'
  test_data_path:  '../data/val_set.csv'

  checkpoint_name: None 
  learning_rate : 0.0001
  lr_gamma: 0.9990     # for exponential learning rate decay
  betas : [0.9, 0.95]

  checkpoint_every_n_train_steps : 100
  save_top_k : 1
  monitor: 'loss'
  mode: 'min'
  log_every_nsteps: 10

  inference_results_folder: './inference_results/'

  seed : 3407

