
model_params:
  block_size: 247    # 247 aa residues (max length of holdout set) 
  vocab_size : 24    # 20 amino acids + special tokens (CLS, X, PAD, MASK)                 
  num_heads: 8 
  dim_head: 64
  num_layers: 6
  emb_dim: 256  

train_params:
  sequence_regularize: True
  seq_flip_prob:  0.0  # regularization: probability of flipping the sequence back-to-front
  seq_mask_prob:  0.05 # regularization: probability of masking an amino acid 
                       # (this masks ~10-15 residues in seq of 242 if prob = 0.05)

  tform_dropout: 0.15
  emb_dropout: 0.15
  mlp_dropout: 0.30

  accelerator : 'gpu'   # cpu, gpu, mps(macbook M2 chip)
  devices: 2
  batch_size: 160
  num_workers: 10
  grad_norm_clip : 1.0
  num_epochs : 1000
  log_dir :        '../lightning_logs/tform_mlp_model/cleaned-3b-data/'
  train_data_path: '../data/q_cleaned_3b_train_set.csv'
  val_data_path:   '../data/q_cleaned_3b_val_set.csv'

  checkpoint_name: None 
  learning_rate : 0.001
  lr_gamma: 0.9995     # for exponential learning rate decay
  betas : [0.9, 0.95]
  checkpoint_every_n_train_steps : 100
  save_top_k : 50
  monitor: 'val_loss'  
  mode: 'min'
  log_every_nsteps: 10
  test_results_folder: '../test_results/tform_mlp_model/cleaned-3b-data/'
  inference_results_folder: '../inference_results/tform_mlp_model/cleaned-3b-data/'

test_params:
  accelerator : 'gpu' # cpu, gpu, mps(macbook M2 chip)
  devices: 1
  batch_size: 160
  num_workers: 2
  checkpoint_name: None 
  test_data_path: '../data/q_cleaned_3b_test_set.csv'

inference_params:
  accelerator : 'gpu' # cpu, gpu, mps(macbook M2 chip)
  devices: 1
  batch_size: 160
  num_workers: 2
  checkpoint_name: None 
  inference_data_path: '../data/alphaseq_data_hold_out.csv'

seed : 3407

